# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "movies" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"year" INTEGER NOT NULL,"imdb_id" VARCHAR NOT NULL,"poster_url" VARCHAR NOT NULL);

# --- !Downs

drop table "movies";

